language: python
python:
  - 3.7
  - 3.8
cache: pip

before_install:
  - python --version
  - pip install -U pip
  - pip install -U flask
  - pip install requests
  - pip install flake8 codecov pytest pytest-cov
  
script: 
  - python -m flake8--ignore=W291 freefree/ --exclude=freefree/app/web/__init__.py
  - python -m pytest tests --cov freefree/app

after_success:
   - codecov
