language: python
python:
  - 3.7
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U flask
  - pip install requests


script: pytest OSS_project/tests
