language: python
python:
  - 3.7
  - 3.8
cache: pip

before_install:
  - python --version
  - pip install -U pip
  - pip install -U flask
  - pip install requests
  - pip install flake8 codecov pytest pytest-cov
  
script: 
  - flake 8 OSS_project/
  - python -m pytest OSS_project/tests --cov OSS_project

after_success:
   - codecov

        

  
